// Expert Guides. Each card is one of the guides published on xplorevietnam.com; the intro and the
// section list are copied from the website page so the preview always matches the real guide.
// Read times are word counts / 230, rounded. Re-run if a guide is rewritten.

export type Tone = "indigo" | "blue" | "violet" | "rose" | "amber" | "emerald" | "cyan" | "orange" | "fuchsia" | "teal";

export type Guide = {
  slug: string;
  title: string;
  text: string;
  icon: string;
  tone: Tone;
  minutes?: number;
  path?: string; // website page, opened in a new tab
  href?: string; // Navigator page (single-button card)
  cta?: string;
  intro?: string;
  sections?: string[];
};

export const GUIDES: Guide[] = [
  {
    slug: "visas",
    title: "Vietnam Visas & Residence Cards",
    text: "The e-visa, work permit, investor and family visas, residence cards and the path to citizenship, and how to choose the right route.",
    icon: "stamp",
    tone: "indigo",
    minutes: 8,
    path: "visas.html",
    intro: "Vietnam is one of the easiest countries in Asia to visit and one of the more complicated to live in long term. There is no retirement visa and no digital nomad visa yet, so the right route depends on why you are here: work, business, family or an extended stay.",
    sections: [
      "Vietnam Residency and Citizenship Timeline",
      "Vietnam E-Visa and Visa Exemptions",
      "Work Permit and Work Visa (LĐ)",
      "Investor Visa (ĐT) and Residence Card",
      "Family Visa (TT) for Spouses and Children",
      "Other Vietnam Visa Options (Brief Overview)",
      "Choosing the Right Vietnam Visa",
      "Final Thoughts",
      "Frequently Asked Questions: Vietnam Visas",
    ],
  },
  {
    slug: "real-estate",
    title: "Renting & Buying a Home in Vietnam",
    text: "What foreigners can and can't own, the purchase process, deposits, fees and mortgages, and how renting works.",
    icon: "house",
    tone: "blue",
    minutes: 10,
    path: "real-estate.html",
    intro: "Foreigners can buy homes in Vietnam, but with limits that differ from most Western countries. You can own an apartment or house in an approved residential project, for an initial term of 50 years, but you can’t own land, and only a share of each project can be sold to foreigners. Most expats rent, at least for their first year.",
    sections: [
      "The Property Purchase Process in Vietnam",
      "What to Know About Vietnam’s Property Market",
      "The Deposit and Sale Contract",
      "Property Inspections",
      "Closing Costs and Fees",
      "Mortgages for Expats in Vietnam",
      "Transferring Money for Your Purchase",
      "Working with a Buyer’s Agent",
      "Renting in Vietnam",
      "Frequently Asked Questions: Property in Vietnam",
    ],
  },
  {
    slug: "cost-of-living",
    title: "Cost of Living in Vietnam",
    text: "The key costs for expats and sample monthly budgets, and how prices change by city and by lifestyle.",
    icon: "wallet",
    tone: "violet",
    minutes: 6,
    path: "cost-of-living.html",
    intro: "The cost of living in Vietnam is low by Western standards, but it varies a lot by city and by lifestyle. Housing is the biggest expense, and central Ho Chi Minh City and the popular expat areas of Hanoi cost the most. Living locally is very cheap. Living like you did at home, with imported food and Western brands, costs a lot more.",
    sections: [
      "Key Cost Considerations for Expats in Vietnam",
      "Sample Monthly Budgets in Vietnam",
      "Final Thoughts on Cost of Living in Vietnam",
      "Frequently Asked Questions: Cost of Living in Vietnam",
    ],
  },
  {
    slug: "healthcare",
    title: "Vietnam Healthcare & Health Insurance Guide",
    text: "How public and private healthcare work, what care costs, the insurance your visa needs, and pharmacies and prescriptions.",
    icon: "heart",
    tone: "rose",
    minutes: 6,
    path: "healthcare.html",
    intro: "Healthcare in Vietnam is affordable, and in the big cities you’ll find modern private and international hospitals with English-speaking doctors. The public system is very cheap but crowded, and it mostly works in Vietnamese. Most expats rely on private care backed by good health insurance, and use public hospitals only for specific needs.",
    sections: [
      "How Healthcare in Vietnam Works",
      "How to Access Public Healthcare in Vietnam",
      "Private Healthcare in Vietnam",
      "Public vs Private Healthcare in Vietnam: What’s Better?",
      "Health Insurance in Vietnam for Expats",
      "What Insurance You Need for Your Vietnam Visa",
      "Pharmacies and Prescriptions in Vietnam",
      "Final Thoughts on Healthcare in Vietnam",
      "Frequently Asked Questions: Healthcare in Vietnam",
    ],
  },
  {
    slug: "schools",
    title: "Schools & Childcare in Vietnam",
    text: "Public, private, bilingual and international school options, homeschooling and childcare, and what families should plan first.",
    icon: "school",
    tone: "amber",
    minutes: 6,
    path: "schools.html",
    intro: "For families with children, school selection is often the most consequential decision in a relocation. Vietnam offers public, private, bilingual and international schools, but in practice almost all expat children attend international or bilingual schools, because public schools teach entirely in Vietnamese. Fees and waiting lists vary a lot, so this is the part of your move to start planning first.",
    sections: [
      "How the Vietnamese Education System Is Structured",
      "International Schools List",
      "Public Schools in Vietnam",
      "Private Schools in Vietnam",
      "International and Bilingual Schools in Vietnam",
      "Homeschooling in Vietnam",
      "Childcare in Vietnam",
      "How XploreVietnam Supports Families",
      "Frequently Asked Questions: Schools in Vietnam",
    ],
  },
  {
    slug: "pets",
    title: "Relocating Pets to Vietnam",
    text: "The documents your pet needs, quarantine and breed rules, flights and timing, and vet care once you arrive.",
    icon: "paw",
    tone: "emerald",
    minutes: 7,
    path: "pets.html",
    intro: "Many expats bring their dogs and cats to Vietnam, and the import rules are simpler than in many countries. There is no mandatory quarantine and no rabies antibody test for entry, as long as your paperwork is correct. The harder parts are usually finding a suitable flight, getting the timing of the documents right, and finding pet-friendly housing once you arrive.",
    sections: [
      "Does Vietnam Require Pet Quarantine?",
      "How Far in Advance Should I Start?",
      "What Documents Does My Pet Need to Enter Vietnam?",
      "Bringing Pets to Vietnam from the US",
      "Bringing Pets to Vietnam from Canada",
      "Bringing Pets to Vietnam from the UK",
      "How Can My Pet Travel to Vietnam?",
      "Are There Breed Restrictions for Vietnam?",
      "What Happens When My Pet Arrives in Vietnam?",
      "Veterinary Care Once You Arrive",
      "Frequently Asked Questions: Relocating Pets to Vietnam",
    ],
  },
  {
    slug: "shipping",
    title: "Shipping Your Belongings to Vietnam",
    text: "Your logistics options, duty-free import of personal effects, what to bring vs. buy locally, and importing a vehicle.",
    icon: "plane",
    tone: "cyan",
    minutes: 4,
    path: "shipping.html",
    intro: "Most expats bring much less to Vietnam than they expect. Most rental apartments come fully furnished, furniture and household goods are affordable, and customs rules for shipping personal effects are strict. Replacing many items locally is often cheaper and simpler than shipping them.",
    sections: [
      "Your Logistics Options",
      "Duty-Free Import of Personal Effects",
      "What to Bring and What to Buy",
      "Importing Your Vehicle",
      "Frequently Asked Questions: Shipping to Vietnam",
    ],
  },
  {
    slug: "taxes",
    title: "Taxes for Expats in Vietnam",
    text: "2026 income tax rates, filing, social insurance, and what U.S., UK and Canadian expats and business owners need to know.",
    icon: "receipt",
    tone: "orange",
    minutes: 6,
    path: "taxes.html",
    intro: "Expats who become tax residents in Vietnam are taxed on their worldwide income, at progressive rates, and must file an annual tax return. Vietnam’s personal income tax law was rewritten in 2025, with lower brackets and higher deductions from 2026. Knowing when your tax residency starts is one of the most important parts of planning your move.",
    sections: [
      "Income Tax Rates in Vietnam (2026)",
      "What Changed in 2026",
      "Filing Taxes in Vietnam",
      "Capital Gains and Property Taxes",
      "VAT and Everyday Taxes",
      "Social Insurance in Vietnam",
      "Taxes for U.S. Expats in Vietnam",
      "Taxes for UK Expats in Vietnam",
      "Taxes for Canadian Expats in Vietnam",
      "Taxes for Business Owners and Freelancers",
      "Final Thoughts on Taxes in Vietnam",
      "Frequently Asked Questions: Taxes in Vietnam",
    ],
  },
  {
    slug: "destinations",
    title: "Where to Live in Vietnam",
    text: "Ho Chi Minh City, Hanoi, Da Nang, Nha Trang, Da Lat and Phu Quoc: the climate, pace of life and expat community in each.",
    icon: "pin",
    tone: "fuchsia",
    minutes: 8,
    path: "destinations.html",
    intro: "Vietnam offers everything from fast-paced megacities to laid-back beach towns and cool mountain retreats. Whether you’re drawn to the energy of Ho Chi Minh City, the history of Hanoi or the beaches of Da Nang, each region has its own climate, pace of life and expat community. Note that since July 2025, Vietnam has merged many provinces and removed the district level of government, so official addresses have changed, but most people still use the old district names, as we do here.",
    sections: [
      "Ho Chi Minh City & Surrounds",
      "Hanoi & the North",
      "Da Nang & the Central Coast",
      "Nha Trang & the South-Central Coast",
      "Da Lat & the Central Highlands",
      "Phu Quoc & the Islands",
      "Frequently Asked Questions: Best Places to Live in Vietnam",
    ],
  },
  {
    slug: "vietnamese",
    title: "Vietnamese Language Resources",
    text: "A free video lesson on the Vietnamese tones, plus our recommended learning partner for live classes with native teachers.",
    icon: "languages",
    tone: "teal",
    href: "/vietnam/partners#vietnamese",
    cta: "Go to Lessons",
  },
];
