// International and international-bilingual schools, researched 29 Sep 2026 from each school's
// published fee schedules and pages (sources listed per school). Fees are annual tuition for the
// most recent published year, converted from VND at 26,300 per US$1 unless noted, and exclude
// application, enrolment, development and capital fees. null = not published / not verified.
// Excluded on purpose: ISSP (closed June 2025), AISVN (dissolved Jan 2026), Saigon Star (unlicensed),
// Palm River Academy, Hoi An (licensed as a language centre, not a school).

export type School = {
  name: string;
  city: "Ho Chi Minh City" | "Hanoi" | "Da Nang" | "Hoi An";
  area: string;
  entry: number | null;
  max: number | null;
  languages: string;
  curriculum: string;
  feeLow: number | null;
  feeHigh: number | null;
  feeYear: string | null;
  sen: "Yes" | "No" | "Unclear";
  website: string;
  email: string;
  phone: string;
  notes: string;
  source: string;
};

export const SCHOOLS: School[] = [
  // ── Ho Chi Minh City ──
  { name: "British International School Ho Chi Minh City (BIS HCMC)", city: "Ho Chi Minh City", area: "Thao Dien / An Phu", entry: 2, max: 18, languages: "English", curriculum: "English National Curriculum, IGCSE, IB DP; CIS, BSO", feeLow: 9370, feeHigh: 38000, feeYear: "2026-27", sen: "Yes", website: "https://www.nordangliaeducation.com/bis-hcmc", email: "", phone: "+84 28 3744 2335", notes: "Applications accepted all year round. Lowest fee is half-day Foundation 1 (full day about $12,670); annual-payment rates. EAL and speech therapy are extra.", source: "https://www.nordangliaeducation.com/bis-hcmc/admissions" },
  { name: "British Vietnamese International School HCMC (BVIS)", city: "Ho Chi Minh City", area: "Binh Hung (Saigon South)", entry: 2, max: 18, languages: "English / Vietnamese", curriculum: "English National Curriculum with Vietnamese programme, IGCSE, A-Levels", feeLow: 9860, feeHigh: 26950, feeYear: "2026-27", sen: "Yes", website: "https://www.nordangliaeducation.com/bvis-hcmc", email: "admissions@bvisvietnam.com", phone: "+84 28 3758 8033", notes: "Bilingual English–Vietnamese school; enrolment open all year. Annual-payment rates. Learning support covers minor learning difficulties.", source: "https://www.nordangliaeducation.com/bvis-hcmc/admissions/tuition-fees" },
  { name: "International School Ho Chi Minh City (ISHCMC)", city: "Ho Chi Minh City", area: "Thao Dien", entry: 2, max: 18, languages: "English", curriculum: "IB (PYP, MYP, DP); CIS, NEASC", feeLow: 10930, feeHigh: 37560, feeYear: "2026-27", sen: "Yes", website: "https://www.ishcmc.com", email: "admissions@ishcmc.edu.vn", phone: "+84 28 3898 9100", notes: "Lowest fee is half-day Early Explorers 2 (full day about $15,060). Supports mild to moderate learning needs. Grades 1–12 also pay an annual development fee.", source: "https://www.ishcmc.com/admissions/tuition-fees/" },
  { name: "ISHCMC – American Academy", city: "Ho Chi Minh City", area: "An Phu (Thao Dien)", entry: 11, max: 18, languages: "English", curriculum: "American curriculum, AP; NEASC, Cognia", feeLow: 23390, feeHigh: 29240, feeYear: "2026-27", sen: "Yes", website: "https://www.aavn.edu.vn", email: "admissions@aavn.edu.vn", phone: "+84 28 3898 9098", notes: "Middle and high school only (Grades 6–12).", source: "https://www.aavn.edu.vn/admissions/tuition-fees/" },
  { name: "Saigon South International School (SSIS)", city: "Ho Chi Minh City", area: "District 7 (Phu My Hung)", entry: 3, max: 18, languages: "English", curriculum: "American standards, AP, IB DP; WASC, CIS", feeLow: 20160, feeHigh: 35150, feeYear: "2026-27", sen: "Yes", website: "https://www.ssis.edu.vn", email: "info@ssis.edu.vn", phone: "+84 28 3622 0870", notes: "Not-for-profit. Rolling admissions; the school advises starting in January for August entry. 6% off if paid in full early.", source: "https://www.ssis.edu.vn/admissions/tuition-and-fees" },
  { name: "Australian International School (AIS)", city: "Ho Chi Minh City", area: "Thu Thiem and Thao Dien", entry: 1.5, max: 18, languages: "English", curriculum: "IB PYP, Cambridge Lower Secondary & IGCSE, IB DP; CIS", feeLow: 11860, feeHigh: 34520, feeYear: "2026-27", sen: "Yes", website: "https://www.aisvietnam.com", email: "info@aisvietnam.com", phone: "+84 28 3742 4040", notes: "Accepts children from 18 months; boarding for Years 7–13. 2026-27 range as reported by VnExpress.", source: "https://www.aisvietnam.com/admissions/fees" },
  { name: "Renaissance International School Saigon (RISS)", city: "Ho Chi Minh City", area: "District 7", entry: 2, max: 18, languages: "English", curriculum: "IB PYP & MYP, Cambridge IGCSE, IB DP; CIS, FOBISIA", feeLow: 7680, feeHigh: 32560, feeYear: "2026-27", sen: "Yes", website: "https://renaissance.edu.vn", email: "", phone: "+84 28 3773 3171", notes: "Lowest fee is half-day Early Years 1. Has an inclusive education team. Annual-payment rates.", source: "https://renaissance.edu.vn/fees/" },
  { name: "The American School (TAS)", city: "Ho Chi Minh City", area: "Binh Trung (Thu Duc)", entry: 1.5, max: 18, languages: "English", curriculum: "American curriculum, IB PYP, AP, IB DP (candidate); WASC", feeLow: 9670, feeHigh: 29160, feeYear: "2026-27", sen: "Yes", website: "https://www.tas.edu.vn", email: "admissions@mytas.edu.vn", phone: "+84 90 904 6223", notes: "EAL support is billed on top of tuition. Learning support for mild learning differences.", source: "https://www.tas.edu.vn/admissions-page/fee-schedule" },
  { name: "European International School HCMC (EIS)", city: "Ho Chi Minh City", area: "Thao Dien", entry: 2, max: 18, languages: "English", curriculum: "IB (PYP, MYP, DP); CIS, WASC", feeLow: 11020, feeHigh: 30950, feeYear: "2026-27", sen: "Unclear", website: "https://www.eishcmc.com", email: "info@eishcmc.com", phone: "+84 28 7300 7257", notes: "English support for non-native speakers included at no extra fee. Annual-payment rates.", source: "https://www.eishcmc.com/admissions/fees" },
  { name: "The Canadian International School (CIS)", city: "Ho Chi Minh City", area: "District 7 (Phu My Hung)", entry: 4, max: 18, languages: "English", curriculum: "Ontario curriculum (OSSD), IB DP", feeLow: 13950, feeHigh: 32900, feeYear: "2026-27", sen: "Yes", website: "https://cis.edu.vn", email: "enquiry@cis.edu.vn", phone: "+84 28 5412 3456", notes: "Has an SEN teacher but cannot accommodate moderate or severe needs; waiting list reported. 2026-27 range as reported by VnExpress.", source: "https://cis.edu.vn/en/admissions/school-fees" },
  { name: "Lycée Français International Marguerite Duras", city: "Ho Chi Minh City", area: "Long Binh (Thu Duc)", entry: 3, max: 18, languages: "French", curriculum: "French national curriculum (AEFE), Brevet, Baccalauréat", feeLow: 9200, feeHigh: 10630, feeYear: "2026-27", sen: "Yes", website: "https://lfiduras.com", email: "sec.direction@lfiduras.com", phone: "", notes: "Fees published in euros; shown at the 'other nationalities' rate (French families pay less). Fixed enrolment window in March.", source: "https://lfiduras.com/index.php/sinscrire-se-reinscrire/" },
  { name: "International German School HCMC (IGS)", city: "Ho Chi Minh City", area: "Binh Trung (Thu Duc)", entry: 2, max: 18, languages: "German / English", curriculum: "German curriculum, IB DP or bilingual GIB; ZfA German School Abroad", feeLow: 8000, feeHigh: 19380, feeYear: "2026-27", sen: "Yes", website: "https://igs-hcmc.org", email: "admissions@igs-hcmc.org", phone: "+84 28 3744 6344", notes: "Intensive German programme for newcomers. Lowest fee is half-day kindergarten; annual-payment rates.", source: "https://igs-hcmc.org/admissions" },
  { name: "The ABC International School (ABCIS)", city: "Ho Chi Minh City", area: "Binh Hung and Nha Be (Saigon South)", entry: 2, max: 18, languages: "English", curriculum: "English National Curriculum, IGCSE, A-Levels; BSO, FOBISIA", feeLow: 7110, feeHigh: 30060, feeYear: "2025-26", sen: "No", website: "https://www.theabcis.com", email: "office@theabcis.com", phone: "+84 28 7308 1828", notes: "School states it does not provide SEN support. Fees from the 2025-26 schedule (Doris); tuition includes uniform, insurance and lunch for younger years.", source: "https://www.theabcis.com/admission/school-fees/" },
  { name: "International Schools of North America (SNA) – Saigon South", city: "Ho Chi Minh City", area: "Binh Hung (Saigon South)", entry: null, max: 18, languages: "English", curriculum: "IB (PYP, MYP, DP); WASC, CIS", feeLow: 19570, feeHigh: 32070, feeYear: "2026-27", sen: "Yes", website: "https://sna.edu.vn", email: "info@sna.edu.vn", phone: "+84 28 7301 9799", notes: "Describes itself as an IB inclusive school with individual education plans. 5–10% early-payment discount.", source: "https://sna.edu.vn/tuition-fees/" },
  { name: "Singapore International School @ Saigon South (SIS)", city: "Ho Chi Minh City", area: "Binh Hung (Saigon South)", entry: 2, max: 18, languages: "English", curriculum: "Singapore + Cambridge (IGCSE, AS/A-Levels); WASC", feeLow: 10670, feeHigh: 25230, feeYear: "2026", sen: "Unclear", website: "https://saigonsouth.sis.edu.vn", email: "enquiry@saigonsouth.sis.edu.vn", phone: "+84 28 7301 3777", notes: "International Programme fees; a cheaper Integrated Programme includes the Vietnamese curriculum.", source: "https://saigonsouth.sis.edu.vn/admissions/school-fees/" },
  { name: "Vietnam Australia International School (VAS)", city: "Ho Chi Minh City", area: "6 campuses (District 7, District 10, Go Vap, Thu Duc…)", entry: null, max: 18, languages: "English / Vietnamese", curriculum: "Cambridge (Primary to A-Level); bilingual tracks with Vietnamese curriculum", feeLow: 10590, feeHigh: 23160, feeYear: "2025-26", sen: "Unclear", website: "https://www.vas.edu.vn", email: "", phone: "", notes: "Fees shown are the fully English CAP International track, Grades 1–12. Bilingual tracks cost less.", source: "https://www.vas.edu.vn/en/school-fee" },
  { name: "Western Australian International School System (WASS)", city: "Ho Chi Minh City", area: "Xuan Hoa (District 3) and Binh Thanh", entry: 2, max: 18, languages: "English / Vietnamese", curriculum: "Western Australian Curriculum, WACE, IB DP; Cognia, CIS", feeLow: null, feeHigh: null, feeYear: null, sen: "Yes", website: "https://wass.edu.vn", email: "schooloffice@wass.edu.vn", phone: "+84 28 7109 5077", notes: "Bilingual and fully international tracks. No current official fee schedule published.", source: "https://wass.edu.vn/en/" },
  { name: "Wellspring Saigon International Bilingual School", city: "Ho Chi Minh City", area: "Binh Thanh and District 7", entry: 6, max: 18, languages: "English / Vietnamese", curriculum: "Vietnamese curriculum + US standards, AP; WASC", feeLow: 8600, feeHigh: 14350, feeYear: "2026-27", sen: "Yes", website: "https://wellspringsaigon.edu.vn", email: "admissions@wellspringsaigon.edu.vn", phone: "+84 28 3840 9292", notes: "Bilingual Grades 1–12, no kindergarten. Annual-payment rates.", source: "https://www.wellspring.edu.vn/co-so/wellspring-saigon" },
  { name: "EMASI International Bilingual Schools", city: "Ho Chi Minh City", area: "Nam Long (District 7) and Van Phuc (Thu Duc)", entry: 2, max: 18, languages: "English / Vietnamese", curriculum: "Cambridge (Primary to A-Level) + Vietnamese curriculum; WASC", feeLow: 5730, feeHigh: 14960, feeYear: "2025-26", sen: "Unclear", website: "https://www.emasi.edu.vn", email: "tuyensinh@emasi.edu.vn", phone: "+84 28 3773 3668", notes: "Bilingual programme. Same fees at both campuses; annual development fee extra.", source: "https://www.emasi.edu.vn/en/tuition-fees/" },
  { name: "Einstein School Ho Chi Minh City (ESH)", city: "Ho Chi Minh City", area: "Phong Phu (Saigon South)", entry: 6, max: 18, languages: "Vietnamese / English", curriculum: "Vietnamese curriculum with Pearson Edexcel English; VCE with Haileybury", feeLow: null, feeHigh: null, feeYear: null, sen: "Unclear", website: "https://esh.edu.vn", email: "", phone: "", notes: "Bilingual school built on the Vietnamese curriculum (formerly Albert Einstein School).", source: "https://esh.edu.vn" },
  { name: "Korean International School HCMC", city: "Ho Chi Minh City", area: "District 7 (Phu My Hung)", entry: null, max: 18, languages: "Korean", curriculum: "Korean national curriculum", feeLow: null, feeHigh: null, feeYear: null, sen: "Unclear", website: "http://kshcm.net", email: "", phone: "", notes: "Serves Korean families.", source: "http://kshcm.net" },
  { name: "The Japanese School in Ho Chi Minh City", city: "Ho Chi Minh City", area: "District 7 (Saigon South)", entry: 6, max: 15, languages: "Japanese", curriculum: "Japanese national curriculum", feeLow: 4800, feeHigh: 4800, feeYear: "2026", sen: "Unclear", website: "https://jschoolhcmc.com", email: "", phone: "+84 28 3638 0012", notes: "For Japanese nationals only. Published as US$400 a month; entrance fee and bus extra.", source: "https://jschoolhcmc.com" },
  { name: "Taipei School in Ho Chi Minh City", city: "Ho Chi Minh City", area: "District 7 (Phu My Hung)", entry: 3, max: 18, languages: "Mandarin", curriculum: "Taiwan national curriculum", feeLow: 4760, feeHigh: 5690, feeYear: "2025-26", sen: "Unclear", website: "https://www.tshcmc.edu.vn", email: "chf-regis@tshcmc.edu.vn", phone: "", notes: "Admits foreign-passport students at higher fees (shown, Grades 1–12). One-time building fund for foreign students.", source: "https://www.tshcmc.edu.vn/p/403-1000-15-1.php" },

  // ── Hanoi ──
  { name: "United Nations International School of Hanoi (UNIS)", city: "Hanoi", area: "Tay Ho (Ciputra)", entry: 3, max: 18, languages: "English", curriculum: "IB (PYP, MYP, DP); CIS, WASC", feeLow: 17460, feeHigh: 39870, feeYear: "2026-27", sen: "Yes", website: "https://www.unishanoi.org", email: "admissions@unishanoi.org", phone: "+84 24 7300 4508", notes: "Published in USD. One-time enrolment fee of US$1,750 plus US$600 application fee.", source: "https://www.unishanoi.org/admissions/tuition-fees" },
  { name: "British International School Hanoi (BIS Hanoi)", city: "Hanoi", area: "Long Bien (Vinhomes Riverside)", entry: 2, max: 18, languages: "English", curriculum: "English National Curriculum, IGCSE, IB DP; CIS, WASC, FOBISIA", feeLow: 9640, feeHigh: 36890, feeYear: "2026-27", sen: "Yes", website: "https://www.nordangliaeducation.com/bis-hanoi", email: "bishanoi@bishanoi.com", phone: "+84 24 3946 0435", notes: "Lowest fee is half-day Foundation 1 (full day about $13,050). EAL support is extra.", source: "https://www.nordangliaeducation.com/bis-hanoi/admissions/tuition-fees" },
  { name: "British Vietnamese International School Hanoi (BVIS)", city: "Hanoi", area: "Thanh Xuan (Royal City)", entry: 2, max: 18, languages: "English / Vietnamese", curriculum: "English National Curriculum, IGCSE, A-Levels; Vietnamese programme", feeLow: 9950, feeHigh: 25150, feeYear: "2026-27", sen: "Yes", website: "https://www.nordangliaeducation.com/bvis-hanoi", email: "enquiry@bvishanoi.com", phone: "+84 981 626 100", notes: "Tuition includes lunch, day trips, learning materials and health insurance.", source: "https://www.nordangliaeducation.com/bvis-hanoi/admissions/tuition-fees" },
  { name: "Concordia International School Hanoi", city: "Hanoi", area: "Dong Anh (Van Tri)", entry: 4, max: 18, languages: "English", curriculum: "US curriculum, AP; WASC", feeLow: 21220, feeHigh: 39500, feeYear: "2026-27", sen: "No", website: "https://www.concordiahanoi.org", email: "admissions@concordiahanoi.org", phone: "+84 24 3795 8878", notes: "Limited support for mild learning needs only; no formal special-needs services.", source: "https://www.concordiahanoi.org/admissions/admissions-faqs" },
  { name: "St. Paul American School Hanoi", city: "Hanoi", area: "Hoai Duc (Splendora)", entry: 6, max: 18, languages: "English", curriculum: "US curriculum (Common Core), AP; Cognia", feeLow: 25320, feeHigh: 32510, feeYear: "2026-27", sen: "Yes", website: "https://stpaulhanoi.com", email: "admissions@stpaulhanoi.com", phone: "+84 24 3399 6464", notes: "Grades 1–12 only. Full-year payment rates.", source: "https://stpaulhanoi.com/admissions/tuition/" },
  { name: "Hanoi International School (HIS)", city: "Hanoi", area: "Ba Dinh", entry: 4, max: 18, languages: "English", curriculum: "IB (PYP, MYP, DP); CIS", feeLow: 16730, feeHigh: 30300, feeYear: "2026-27", sen: "Yes", website: "https://www.hisvietnam.com", email: "admissions@hisvietnam.com", phone: "+84 24 3832 8140", notes: "Refundable security deposit and one-time enrolment fee on top of tuition.", source: "https://www.hisvietnam.com/admissions/tuition-and-fees" },
  { name: "Lycée Français Alexandre Yersin (LFAY)", city: "Hanoi", area: "Long Bien", entry: 3, max: 18, languages: "French", curriculum: "French national curriculum (AEFE); American International Section", feeLow: 5310, feeHigh: 9870, feeYear: "2026-27", sen: "Unclear", website: "https://lfay.com.vn", email: "secretariat@lfay.com.vn", phone: "+84 24 3843 6779", notes: "Fees vary by nationality (French nationals pay least); range from Doris. Registration window Feb–Mar.", source: "https://lfay.com.vn/en/school-fees/" },
  { name: "Singapore International School (SIS) Hanoi", city: "Hanoi", area: "Ba Dinh (Van Phuc), Tay Ho (Ciputra), Hoang Mai (Gamuda)", entry: 1.5, max: 18, languages: "English", curriculum: "Singapore + Cambridge (IGCSE, AS/A-Levels); WASC", feeLow: 7860, feeHigh: 25230, feeYear: "2026", sen: "Unclear", website: "https://vanphuc.sis.edu.vn", email: "enquiry@vanphuc.sis.edu.vn", phone: "+84 24 7304 2777", notes: "Fees differ by campus and between International and Integrated programmes. Lowest is half-day Pre-Nursery.", source: "https://vanphuc.sis.edu.vn/academic/international-programme/" },
  { name: "Reigate Grammar School Vietnam", city: "Hanoi", area: "Hoang Mai", entry: 3, max: 18, languages: "English", curriculum: "English National Curriculum, IGCSE, IB (PYP, DP); COBIS, FOBISIA", feeLow: 15270, feeHigh: 37330, feeYear: "2026-27", sen: "Unclear", website: "https://reigategrammar.edu.vn", email: "inquiry@reigategrammar.edu.vn", phone: "+84 24 3540 9183", notes: "EAL support is extra.", source: "https://reigategrammar.edu.vn/tuition-fees.htm" },
  { name: "Dwight School Hanoi", city: "Hanoi", area: "Hoang Mai", entry: 3, max: 18, languages: "English", curriculum: "IB (PYP, MYP, DP); CIS member", feeLow: 13690, feeHigh: 38120, feeYear: "2026-27", sen: "Yes", website: "https://dwighthanoi.org", email: "admissions@dwighthanoi.org", phone: "+84 24 7300 6300", notes: "Opened August 2024. Quest learning support has extra fees.", source: "https://dwighthanoi.org/admissions/fees/" },
  { name: "Brighton College Vietnam", city: "Hanoi", area: "Gia Lam (Vinhomes Ocean Park)", entry: 3, max: 18, languages: "English", curriculum: "English National Curriculum, IGCSE, IB DP; FOBISIA", feeLow: null, feeHigh: null, feeYear: null, sen: "No", website: "https://brightoncollege.edu.vn", email: "", phone: "+84 1800 6010", notes: "Reported as unable to accommodate pupils with special needs at present. Fee schedule not publicly accessible.", source: "https://brightoncollege.edu.vn/adm/fees-scholarships/" },
  { name: "The International School @ ParkCity Hanoi (ISPH)", city: "Hanoi", area: "Ha Dong (ParkCity)", entry: 3, max: 18, languages: "English", curriculum: "English National Curriculum / IPC, IGCSE, AS/A-Levels", feeLow: null, feeHigh: null, feeYear: null, sen: "Yes", website: "https://isph.edu.vn", email: "admissions@isph.edu.vn", phone: "+84 934 455 228", notes: "Fee page not accessible; directories disagree.", source: "https://isph.edu.vn" },
  { name: "Horizon International Bilingual School", city: "Hanoi", area: "Tay Ho", entry: null, max: 18, languages: "English / Vietnamese", curriculum: "Cambridge (Primary to A-Level); bilingual track adds Vietnamese curriculum", feeLow: 11960, feeHigh: 23080, feeYear: "2026-27", sen: "Unclear", website: "https://www.horizon.edu.vn", email: "infohanoi@hibsvietnam.com", phone: "+84 24 3719 4953", notes: "International programme fees, from Doris.", source: "https://www.horizon.edu.vn" },
  { name: "The Dewey Schools", city: "Hanoi", area: "Bac Tu Liem (Tay Ho Tay), Cau Giay, Gia Lam", entry: 6, max: 18, languages: "English / Vietnamese", curriculum: "Bilingual and international programmes with Vietnamese curriculum; IB DP", feeLow: 16460, feeHigh: 25360, feeYear: "2025-26", sen: "Unclear", website: "https://thedeweyschools.edu.vn", email: "info.tht@thedeweyschools.edu.vn", phone: "+84 24 7302 2288", notes: "Fees shown are the Journey International programme (95% English); bilingual programmes cost less.", source: "https://thedeweyschools.edu.vn/en/tuition-and-fees/" },
  { name: "Wellspring Hanoi International Bilingual School", city: "Hanoi", area: "Long Bien", entry: 6, max: 18, languages: "Vietnamese / English", curriculum: "Vietnamese curriculum bilingual; AP and US dual diploma; WASC", feeLow: 6890, feeHigh: 9650, feeYear: "2026-27", sen: "Yes", website: "https://wellspring.edu.vn", email: "tuyensinh@wellspring.edu.vn", phone: "+84 24 7305 8668", notes: "Vietnamese bilingual school; international track for Grades 10–12 costs more.", source: "https://wellspring.edu.vn" },
  { name: "The Olympia Schools", city: "Hanoi", area: "Nam Tu Liem", entry: 4, max: 18, languages: "Vietnamese / English", curriculum: "Vietnamese curriculum bilingual; IB DP; US integrated programme; WASC", feeLow: 5670, feeHigh: 9050, feeYear: "2026-27", sen: "Unclear", website: "https://theolympiaschools.edu.vn", email: "tuyensinh@theolympiaschools.edu.vn", phone: "+84 24 6267 7999", notes: "Vietnamese private bilingual school; integrated US programmes cost up to about $25,920.", source: "https://theolympiaschools.edu.vn/en" },
  { name: "Hanoi Academy International Bilingual School", city: "Hanoi", area: "Tay Ho (Ciputra)", entry: 3, max: 18, languages: "Vietnamese / English", curriculum: "Vietnamese curriculum bilingual with Cambridge (IGCSE, A-Level)", feeLow: 4430, feeHigh: 6270, feeYear: "2026-27", sen: "Unclear", website: "https://hanoiacademy.edu.vn", email: "info@hanoiacademy.edu.vn", phone: "+84 24 3743 0135", notes: "Vietnamese bilingual school. Fees from Doris.", source: "https://hanoiacademy.edu.vn" },
  { name: "Korean International School in Hanoi (KISH)", city: "Hanoi", area: "Nam Tu Liem", entry: 6, max: 18, languages: "Korean", curriculum: "Korean national curriculum", feeLow: 10630, feeHigh: 14500, feeYear: "2026-27", sen: "Unclear", website: "http://www.hanoischool.net", email: "", phone: "", notes: "Korean-curriculum school taught mainly in Korean. Fees from Doris.", source: "http://www.hanoischool.net" },
  { name: "Japanese School of Hanoi", city: "Hanoi", area: "Nam Tu Liem (My Dinh)", entry: 6, max: 15, languages: "Japanese", curriculum: "Japanese national curriculum", feeLow: null, feeHigh: null, feeYear: "2026", sen: "Unclear", website: "https://jsh.edu.vn", email: "school@jsh.edu.vn", phone: "+84 24 3764 9877", notes: "School for Japanese children. Published as US$500 a month, paid by semester.", source: "https://jsh.edu.vn/transfer/tuition/" },

  // ── Da Nang ──
  { name: "Singapore International School @ Da Nang", city: "Da Nang", area: "Ngu Hanh Son", entry: 1.5, max: 18, languages: "English", curriculum: "Singapore + Cambridge (IGCSE, AS/A-Levels); WASC", feeLow: 10670, feeHigh: 25230, feeYear: "2026-27", sen: "Unclear", website: "https://danang.sis.edu.vn", email: "enquiry@danang.sis.edu.vn", phone: "+84 236 730 1777", notes: "International track; a cheaper bilingual Integrated Programme is also offered. Half-day nursery from about $7,860.", source: "https://danang.sis.edu.vn/admissions/school-fees/" },
  { name: "APU American International School – Da Nang", city: "Da Nang", area: "Ngu Hanh Son", entry: 3, max: 18, languages: "English", curriculum: "American curriculum, AP; Cognia", feeLow: 9030, feeHigh: 21630, feeYear: "2026-27", sen: "Unclear", website: "https://www.apu.edu.vn/da-nang", email: "info@apu.edu.vn", phone: "+84 236 3928 664", notes: "Also runs a bilingual programme; English Language Development support. Fees from Doris.", source: "https://www.apu.edu.vn/da-nang" },
  { name: "Odyssey International School", city: "Da Nang", area: "Dien Ban (between Da Nang and Hoi An)", entry: 3, max: 18, languages: "English", curriculum: "IB candidate school (PYP, MYP, DP); CIS member", feeLow: 7910, feeHigh: 22740, feeYear: "2026-27", sen: "Unclear", website: "https://www.odyssey.edu.vn", email: "admissions@odyssey.edu.vn", phone: "+84 938 688 600", notes: "IB candidate, not yet authorised. Annual campus fee and EAL fee extra.", source: "https://www.odyssey.edu.vn/tuition-and-fees" },
  { name: "The St. Nicholas School", city: "Da Nang", area: "Cam Le (Hoa Xuan)", entry: 0.7, max: 18, languages: "English", curriculum: "American curriculum; US diploma via Mizzou Academy; AP", feeLow: 5650, feeHigh: 9320, feeYear: "2026-27", sen: "Unclear", website: "https://sns.edu.vn", email: "admissions1@sns.edu.vn", phone: "+84 931 972 972", notes: "Kindergarten from 8 months. Grades 9–12 also pay a Mizzou course fee (about $5,700).", source: "https://sns.edu.vn/tuyen-sinh/hoc-phi" },
  { name: "Sky-Line School", city: "Da Nang", area: "Hai Chau (plus a campus near Hoi An)", entry: 1.5, max: 18, languages: "Vietnamese / English", curriculum: "Vietnamese curriculum + Cambridge English; dual-diploma track", feeLow: null, feeHigh: null, feeYear: null, sen: "Unclear", website: "https://skylineschool.edu.vn", email: "", phone: "+84 236 378 7777", notes: "Vietnamese private school system that accepts foreign pupils. No per-grade fee schedule published.", source: "https://skylineschool.edu.vn" },
  { name: "UK Academy International Bilingual School – Da Nang", city: "Da Nang", area: "Thanh Khe", entry: null, max: 18, languages: "English / Vietnamese", curriculum: "Vietnamese curriculum + Oxford International Curriculum; IGCSE, A-Level", feeLow: null, feeHigh: null, feeYear: null, sen: "Unclear", website: "https://uka.edu.vn/en/office/uka-da-nang/", email: "info@uka.com.vn", phone: "+84 236 7305 588", notes: "Bilingual school in the Nguyen Hoang Group. Fees not published.", source: "https://uka.edu.vn/en/office/uka-da-nang/" },
  { name: "Little Giants International Kindergarten", city: "Da Nang", area: "Ngu Hanh Son", entry: 2, max: 6, languages: "English", curriculum: "British EYFS", feeLow: 4520, feeHigh: 4930, feeYear: "2025-26", sen: "Unclear", website: "https://littlegiantskindergarten.com", email: "administrator@littlegiantskindergarten.com", phone: "+84 236 3933 600", notes: "Kindergarten only. Full-time rate paid annually; half-day option available.", source: "https://littlegiantskindergarten.com/fees/" },
  { name: "Cocoon Montessori Preschool", city: "Da Nang", area: "Hai Chau", entry: 1.25, max: 6, languages: "English", curriculum: "Montessori (AMI-trained teachers)", feeLow: null, feeHigh: null, feeYear: null, sen: "Unclear", website: "https://cocoon.edu.vn/en", email: "admin@cocoon.edu.vn", phone: "+84 905 366 576", notes: "Preschool only. Fees on request.", source: "https://cocoon.edu.vn/en" },

  // ── Hoi An ──
  { name: "Hoi An International School (HAIS)", city: "Hoi An", area: "Tan An", entry: 1.5, max: 18, languages: "English / Vietnamese", curriculum: "Cambridge (EYFS, Primary, Lower Secondary, IGCSE, A-Level)", feeLow: 4940, feeHigh: 19390, feeYear: "2026-27", sen: "Unclear", website: "https://hais.edu.vn", email: "admissions@hais.edu.vn", phone: "+84 235 6518 518", notes: "Under-3s are bilingual; English-only International Early Years from age 3 (about $8,170). Separate Vietnamese-curriculum primary track.", source: "https://hais.edu.vn/tuition-fees/" },
];

export const CITIES = ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hoi An"] as const;

export const CURRICULA: { value: string; label: string; match: RegExp }[] = [
  { value: "ib", label: "IB", match: /\bIB\b/ },
  { value: "british", label: "British / Cambridge", match: /English National|Cambridge|IGCSE|A-Level|EYFS|IPC|Oxford/i },
  { value: "american", label: "American", match: /American|US |US$|AP\b|Common Core/ },
  { value: "australian", label: "Australian", match: /Australian|WACE|VCE/ },
  { value: "canadian", label: "Canadian", match: /Ontario/ },
  { value: "singapore", label: "Singapore", match: /Singapore/ },
  { value: "french", label: "French", match: /French/ },
  { value: "german", label: "German", match: /German/ },
  { value: "vietnamese", label: "Vietnamese bilingual", match: /Vietnamese curriculum|Vietnamese programme/ },
  { value: "montessori", label: "Montessori", match: /Montessori/ },
];
